spring.application.name=order-service

spring.datasource.url=jdbc:postgresql://localhost:5432/order
spring.datasource.username=thaituan
spring.datasource.password=123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8082

# Eureka
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
spring.security.user.name=eureka
spring.security.user.password=password

spring.kafka.bootstrap-servers=localhost:9092

# Actuator and Prometheus endpoints
management.endpoint.health.show-details=always
management.endpoints.web.exposure.include=health, prometheus
management.tracing.sampling.probability=1.0

# Resilience4j
# Number of tracked requests
resilience4j.circuitbreaker.instances.inventory-service.sliding-window-size=5
# Open the circuit when 50% of requests fail
resilience4j.circuitbreaker.instances.inventory-service.failureRateThreshold=50
# Try half-open state again after 10 seconds
resilience4j.circuitbreaker.instances.inventory-service.waitDurationInOpenState=10s
# Number of test calls allowed in half-open state
resilience4j.circuitbreaker.instances.inventory-service.permittedNumberOfCallsInHalfOpenState=2
# Mark a call as slow if it takes more than 2 seconds
resilience4j.circuitbreaker.instances.inventory-service.slowCallDurationThreshold=2s
# Open the circuit when 50% of calls are slow
resilience4j.circuitbreaker.instances.inventory-service.slowCallRateThreshold=50
# Retry failed calls up to 3 times
resilience4j.retry.instances.inventory-service.max-attempts=3
# Wait 2 seconds between retries
resilience4j.retry.instances.inventory-service.waitDuration=2s
resilience4j.retry.instances.inventory-service.retryExceptions=org.springframework.web.client.HttpServerErrorException

resilience4j.timelimiter.instances.inventory-service.timeout-duration=10s
