services:
  finally:
    build: .
    ports:
      - "8000:8000"
    environment:
      PYTHONUNBUFFERED: "1"
    env_file:
      - .env
    volumes:
      - finally-data:/app/db
    restart: unless-stopped

volumes:
  finally-data:
    driver: local
