spring.application.name=notification-service
server.port=8084

#Eureka
eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
spring.security.user.name=eureka
spring.security.user.password=password
eureka.instance.prefer-ip-address=true

# Kafka Producer Configuration
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}

user-service.base-url=${USER_SERVICE_URL:http://user-service:8081}

#spring.data.mongodb.uri=mongodb://localhost:27017/database


#Off Database
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
spring.jpa.hibernate.ddl-auto=none

#Mail
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=d298ef0af3b568
spring.mail.password=9c6bfe29fc1e3a
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
