<<<<<<< HEAD
<<<<<<< HEAD
spring.application.name=discovery-server






=======
=======
>>>>>>> dev
spring.application.name=discovery-server






<<<<<<< HEAD
>>>>>>> 5097b7c3 (Tuan07/Init commit for Tuan07)
=======
>>>>>>> dev
